### ISSUE TITLE
leet decoder

### ISSUE THREAD

**Issue by Doubleendedqueue** [HCDevelopers/MultiEncoder#6]
I am not sure if I messed up the merge of noize pull request, but the leet speak doesn't decode correctly:

Encodings/encryptions (type "-i name" to get a description): leet
Encode (e) or decode (d)? d
Text: |-|3||o yo|_| |337 5p34|< f4||

> leet: hell0 y0l_l leet spealc fan

Result: hell0 y0l_l leet spealc fan

The output should be: Hello you leet speak fan

**Comment by AnimeshShaw** [comment]
leet speak should be dropped since they always cause a lot if trouble. Their output also hinders with several other encoding algs too. Also the outputs are not correct in most of the cases.

**Comment by Doubleendedqueue** [comment]
Mh, probably.

**Comment by AnimeshShaw** [comment]
So should we drop support for l33t ?
