### ISSUE TITLE
Reverse instance has no __call__ method

### ISSUE THREAD

**Issue by Doubleendedqueue** [HCDevelopers/MultiEncoder#9]
deque:~/git/multiencoder-<✓>:$ python multiencoder.py 
Traceback (most recent call last):
  File "multiencoder.py", line 27, in <module>
    'reverse' : reverse(), 'rot13' : rot13, 'binary' : binary,
AttributeError: Reverse instance has no **call** method

**Comment by AnimeshShaw** [comment]
Reverse fixed. I actually did the changes to the new UI file but forgot to do it here. Okay now it should be fixed.
